---
title: "Untitled"
author: "Derek Newberger"
date: "5/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r library, echo=FALSE, message=FALSE, warning=FALSE}
library(devtools)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(metacoder)
library(phyloseq)
library(MicEco)
library(reticulate)
library(RColorBrewer)
library(readxl)
library(tidyverse)
library(vegan)
library(ggrepel)
library(pastecs)
```

```{r setup, echo=FALSE}
source("myFunctions.R")
```

```{r import}
# use custom emu_to_phyloseq function to create phyl
P.A <- emu_to_phyloseq(RA_file='/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/Minion_DD_1/EMU.rel_abund.finalDD1.csv',
                                              meta_file='/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/Minion_DD_1/demultiplexDD_1.xlsx', 
                       sheet='DenDivA', range='A1:P65',
                       sample_names='name',
                       run_name='demultiplexDD_1')

P.B <- emu_to_phyloseq(RA_file='/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/Minion_DD_2/Derek_DD2.EMU.rel_abund.final.csv',
                       meta_file='/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/Minion_DD_2/demultiplex_DD2.xlsx', 
                       sheet='DenDivB', range='A1:P51',
                       sample_names='name',
                       run_name='demultiplexDD_2')

# merge all imported datasets
P.relDenDiv <- merge_phyloseq(P.A, P.B)
```

```{r import2}
# save combined relative abundance phyloseq object
saveRDS(P.relDenDiv, '/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')

# convert EMU rel abundances to count data using final number of sequence reads
P.count <- P.relDenDiv
for (n in 1:nsamples(P.count)) {
  otu_table(P.count)[,n] <- round(otu_table(P.count)[,n] * sample_data(P.count)$final[n], 0)
}

# save combined count phyloseq object
saveRDS(P.count, '/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.count.RDS')
```

```{r}
tab <- otu_table(P.count)
class(tab) <- "matrix" # as.matrix() will do nothing
## you get a warning here, but this is what we need to have
tab <- t(tab) # transpose observations to rows
rare <- rarecurve(tab, step=600, lwd=2, ylab="OTU",  label=F)
```
## Control data

```{r}
# import phyloseq object created above
P.count <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.count.RDS')

# select zymo controls only (count)
P.zymos <- subset_samples(P.count, Type == 'Zymo') # type: sample, zymo, blank
rich <- plot_richness(P.zymos, x="name", measures=c('Observed'))
rich

# select water controls only
P.waters <- subset_samples(P.count, Type == 'H2O')
rich <- plot_richness(P.waters, x="name", measures=c('Observed')) 
# Observed it literally a type of richness like Shannon
rich

# select CalEXn controls only
P.calexn <- subset_samples(P.count, Type == 'CalEXn')
rich <- plot_richness(P.calexn, x="name", measures=c('Observed')) 
# Observed is literally a type of richness like Shannon
rich
```

```{r rich sample data}
# select soil samples only
colnames(P.count)
P.soils <- subset_samples(P.count, Type == 'Soil' & Density_Diversity != 'pre')
P.soils

# summary of sample reads
summary(sample_sums(P.soils))

# find a suitable cutoff for remove low-read samples
cutoff <- quantile(sample_sums(P.soils), 0.1)
cutoff

# remove reads with low sequence numbers (< 1st quantile)
P.soils <- prune_samples(sample_sums(P.soils) >= cutoff, P.soils)
P.soils

# richness unrarefied
rich <- plot_richness(P.soils, x="name", measures=c('Observed'))
gDF <- rich$data

# richness rarefied
P.rare <- rarefy_even_depth(P.soils, rngseed=TRUE)
rich.rare <- plot_richness(P.rare, x="name", measures=c('Observed'))
gDF.rare <- rich.rare$data
```

```{r rich fig 1, fig.width=11, fig.height=6, fig.cap="Sequence reads for each trt"}
# Plot reads by site and library
p <- ggplot(gDF, aes(x=Density_Diversity, y=final, fill=Type)) +
  geom_boxplot() +
  scale_y_continuous(labels = function(x) format(x, big.mark = ",",
                                                 scientific = FALSE)) +
  scale_fill_brewer(palette='Set3') +
  # facet_grid(Plant ~ Soil) +
  labs(y='Sequence Reads', x='Treatment') +
  theme_dan() +
    theme(axis.text.x = element_text(angle = 45, hjust=1, size=34)) +
  theme_classic() +
  theme(axis.title=element_text(size=14,face="bold"))

p
ggsave(p, file='/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/Reads_site.pdf', width=11, height=6)
```

```{r rich fig 2, fig.width=11, fig.height=6, fig.cap="Species richness for each trt"}
# Plot richness by site and library
p <- ggplot(gDF, aes(x=Density_Diversity, y=value, fill=Type)) +
  geom_boxplot() +
  scale_y_continuous(labels = function(x) format(x, big.mark = ",",
                                                 scientific = FALSE)) +
  scale_fill_brewer(palette='Set3') +
  # facet_grid(Plant ~ Soil) +
  labs(y='Species Richness', x='') +
  theme_dan() +
    theme(axis.text.x = element_text(angle = 45, hjust=1, size=34)) +
  theme(axis.title=element_text(size=14,face="bold"))
p
ggsave(p, file='/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/Richness_site.pdf', width=11, height=6)
```


```{r rich fig 2a, fig.width=11, fig.height=6, fig.cap="Species richness for each trt - rarefied."}
# Plot richness by site and library
p <- ggplot(gDF.rare, aes(x=Density_Diversity, y=value, fill=Type)) +
  geom_boxplot() +
  scale_y_continuous(labels = function(x) format(x, big.mark = ",",
                                                 scientific = FALSE)) +
  scale_fill_brewer(palette='Set3') +
  # facet_grid(Plant ~ Soil) +
  labs(y='Species Richness', x='') +
  theme_dan() +
  theme(axis.text.x=element_text(angle=90))
p
ggsave(p, file='/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/Richness_rarefied_site.pdf', width=11, height=6)
```
## Estimate Phylum Relative Abundances

```{r rel_abund data 1}
# import data file
P.relDenDiv <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')

# remove samples with < 10000 reads
P.relDenDiv <- subset_samples(P.relDenDiv, final >= 10000)

# pool by phyla
rank <- 'phylum'
P.glom <- phyloseq::tax_glom(P.relDenDiv, taxrank=rank, NArm=FALSE)

# Select soils only
P.soils <- phyloseq::subset_samples(P.glom, Type == 'Soil')

# get top 10 taxa
TopNOTUs = names(sort(taxa_sums(P.soils), TRUE)[1:10])
P.10 = phyloseq::prune_taxa(TopNOTUs, P.soils)

# extract all data from phyloseq object
d <- psmelt(P.10)
```

```{r rel_abund fig 1, fig.width=11, fig.height=8, fig.cap="Relative abundance by phylum."}
# order samples by Fertilizer and Rate (using forcats library)
d$name <- factor(d$name)
d$Diversity <- factor(d$Diversity)
d$Density <- factor(d$Density)
d$name <- forcats::fct_reorder2(d$name, d$Density, d$Diversity)

p <- ggplot(d, aes(x=name, y=Abundance, fill=phylum), color='grey' ) +
  geom_bar(position='stack', stat='summary', fun='mean') +
  # facet_wrap(Soil ~ Plant, scales='free') +
  scale_fill_brewer(palette='Set3', direction=-1) +
  labs(x='', y='Abundance', fill='') +
  theme_dan() +
    theme(axis.text.x = element_text(angle = 90, hjust=1, size=18)) +
  theme(axis.title=element_text(size=14,face="bold"))
p
ggsave(filename='/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/Phylum.Rel_Abundance.pdf', w=11, h=8, plot=p)
```

## Principal Coordinates Analysis

```{r pcoa data 1}
P.relDenDiv <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')
P.relDenDiv <- subset_samples(P.relDenDiv, Type == 'Soil')

# remove samples with < 10000 reads
# P.relDenDiv <- subset_samples(P.relDenDiv, final >= 10000)

# remove taxa with column sums = 0, Stopped working, says unsupported class: phyloseq but the function requires a phyloseq
# P.relDenDiv = filter_taxa(P.relDenDiv, function(x) sum(x) > 0, TRUE)

# get meta data
d <- data.frame(sample_data(P.relDenDiv))

# get otu table for calculating distances
data <- data.frame(t(otu_table(P.relDenDiv)))
data <- sqrt(data) # hellinger's transformation (sqrt of rel abund)

# Create distance matrix from PLFA data
dist <- vegdist(data, method='bray')

# run PCoA for different treatment groups
ord <- capscale(dist ~ Density * Diversity, data=d)
#summary(ord)

# perMANOVA test
adonis2(dist ~ Density * Diversity, data=d, perm=999, by="margin")

### get eigenvalues and proportion explained
ev <- eigenvals(ord)
Axis1_exp = round(ev[1] / sum(ev) * 100, 1)
Axis2_exp = round(ev[2] / sum(ev) * 100, 1)

### get PC axes
axes <- as.data.frame(vegan::scores(ord, display="sites", choices=c(1:2)))
names(axes) <- c("Axis1", "Axis2")
axes <- cbind(d, axes)
```

```{r pcoa fig 1, fig.width=11, fig.height=6, fig.cap="PCoA using species and Bray-Curtis distance."}
# make graph
p <- ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Diversity, shape=Density), color='black') +
  geom_point(size=6) +
  # facet_grid(Soil ~ Plant) +
  scale_fill_brewer(palette = 'Set3') +
  scale_shape_manual(values=c(21,22,23)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 7)))) + # change this number based on the error
  labs(title='PCoA - DNA',
       subtitle='Bray-Curtis - Species',
       x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  # stat_ellipse(geom = "path", type="norm", level=0.95, aes(color = Secondary.Lab)) +
  scale_color_brewer(palette = 'Set3') +
  theme_dan()
p
ggsave(p, file='/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/PCoA.Species.Bray.pdf', width=11, height=6)
```

```{r}
#subset data
axes_DivA <- axes %>%
  filter(Diversity=='A')
axes_DivB <- axes %>%
  filter(Diversity=='B')
axes_DivF <- axes %>%
  filter(Diversity=='F')
axes_DivAB <- axes %>%
  filter(Diversity=='AB')
axes_DivAF <- axes %>%
  filter(Diversity=='AF')
axes_DivBF <- axes %>%
  filter(Diversity=='BF')
axes_DivABF <- axes %>%
  filter(Diversity=='ABF')
axes_Den1 <- axes %>%
  filter(Density=='1')
axes_Den24 <- axes %>%
  filter(Density=='24')
axes_Den48 <- axes %>%
  filter(Density=='48')
axes_DenDivA1 <- axes %>%
  filter(Density_Diversity=='A1')
axes_DenDivA24 <- axes %>%
  filter(Density_Diversity=='A24')
axes_DenDivA48 <- axes %>%
  filter(Density_Diversity=='A48')
axes_DenDivB1 <- axes %>%
  filter(Density_Diversity=='B1')
axes_DenDivB24 <- axes %>%
  filter(Density_Diversity=='B24')
axes_DenDivB48 <- axes %>%
  filter(Density_Diversity=='B48')
axes_DenDivF1 <- axes %>%
  filter(Density_Diversity=='F1')
axes_DenDivF24 <- axes %>%
  filter(Density_Diversity=='F24')
axes_DenDivF48 <- axes %>%
  filter(Density_Diversity=='F48')
axes_DenDivAB1 <- axes %>%
  filter(Density_Diversity=='AB1')
axes_DenDivAB24 <- axes %>%
  filter(Density_Diversity=='AB24')
axes_DenDivF24 <- axes %>%
  filter(Density_Diversity=='F24')
axes_DenDivF48 <- axes %>%
  filter(Density_Diversity=='F48')
axes_DenDivAB1 <- axes %>%
  filter(Density_Diversity=='AB1')
axes_DenDivAB24 <- axes %>%
  filter(Density_Diversity=='AB24')
axes_DenDivAB48 <- axes %>%
  filter(Density_Diversity=='AB48')
axes_DenDivAF1 <- axes %>%
  filter(Density_Diversity=='AF1')
axes_DenDivAF24 <- axes %>%
  filter(Density_Diversity=='AF24')
axes_DenDivAF48 <- axes %>%
  filter(Density_Diversity=='AF48')
axes_DenDivBF1 <- axes %>%
  filter(Density_Diversity=='BF1')
axes_DenDivBF24 <- axes %>%
  filter(Density_Diversity=='BF24')
axes_DenDivBF48 <- axes %>%
  filter(Density_Diversity=='BF48')
axes_DenDivABF1 <- axes %>%
  filter(Density_Diversity=='ABF1')
axes_DenDivABF24 <- axes %>%
  filter(Density_Diversity=='ABF24')
axes_DenDivABF48 <- axes %>%
  filter(Density_Diversity=='ABF48')
```

```{r}
ggplot(data=axes_DivA, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity)) +
  geom_point(size=6) +
  scale_fill_brewer(palette = 'Set2') +
  scale_shape_manual(values=c(21,22,23)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 1)))) +
  labs(x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  scale_color_brewer(palette = 'Set2') +
  theme_few()
```

```{r}
ggplot(data=axes_DivB, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity)) +
  geom_point(size=6) +
  scale_fill_brewer(palette = 'Set2') +
  scale_shape_manual(values=c(21,22,23)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 1)))) +
  labs(x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  scale_color_brewer(palette = 'Set2') +
  theme_few()
```

```{r}
ggplot(data=axes_DivF, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity)) +
  geom_point(size=6) +
  scale_fill_brewer(palette = 'Set2') +
  scale_shape_manual(values=c(21,22,23)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 1)))) +
  labs(x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  scale_color_brewer(palette = 'Set2') +
  theme_few()
```

```{r}
ggplot(data=axes_DivAB, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity)) +
  geom_point(size=6) +
  scale_fill_brewer(palette = 'Set2') +
  scale_shape_manual(values=c(21,22,23)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 1)))) +
  labs(x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  scale_color_brewer(palette = 'Set2') +
  theme_few()
```

```{r}
ggplot(data=axes_DivAF, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity)) +
  geom_point(size=6) +
  scale_fill_brewer(palette = 'Set2') +
  scale_shape_manual(values=c(21,22,23)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 1)))) +
  labs(x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  scale_color_brewer(palette = 'Set2') +
  theme_few()
```

```{r}
ggplot(data=axes_DivBF, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity)) +
  geom_point(size=6) +
  scale_fill_brewer(palette = 'Set2') +
  scale_shape_manual(values=c(21,22,23)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 1)))) +
  labs(x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  scale_color_brewer(palette = 'Set2') +
  theme_few()
```

```{r}
ggplot(data=axes_DivABF, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity)) +
  geom_point(size=6) +
  scale_fill_brewer(palette = 'Set2') +
  scale_shape_manual(values=c(21,22,23)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 1)))) +
  labs(x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  scale_color_brewer(palette = 'Set2') +
  theme_few()
```

```{r}
ggplot(data=axes_Den1, aes(x=Axis1, y=Axis2, fill=Diversity, shape=Density)) +
  geom_point(size=6) +
  scale_fill_brewer(palette = 'Set2') +
  scale_shape_manual(values=c(21,22,23,24,25,26,27)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 1)))) +
  labs(x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  scale_color_brewer(palette = 'Set2') +
  theme_few()
```

```{r}
ggplot(data=axes_Den24, aes(x=Axis1, y=Axis2, fill=Diversity, shape=Density)) +
  geom_point(size=6) +
  scale_fill_brewer(palette = 'Set2') +
  scale_shape_manual(values=c(21,22,23,24,25,26,27)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 1)))) +
  labs(x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  scale_color_brewer(palette = 'Set2') +
  theme_few()
```

```{r}
ggplot(data=axes_Den48, aes(x=Axis1, y=Axis2, fill=Diversity, shape=Density)) +
  geom_point(size=6) +
  scale_fill_brewer(palette = 'Set2') +
  scale_shape_manual(values=c(21,22,23,24,25,26,27)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 1)))) +
  labs(x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  scale_color_brewer(palette = 'Set2') +
  theme_few()
```

```{r pcoa fig 1, fig.width=11, fig.height=6, fig.cap="PCoA using species and Bray-Curtis distance."}
# make graph
p <- ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Alfalfa, shape=Density), color='black') +
  geom_point(size=6) +
  # facet_grid(Soil ~ Plant) +
  scale_fill_brewer(palette = 'Set3') +
  scale_shape_manual(values=c(21,22,23)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 2)))) + # change this number based on the error
  labs(title='PCoA - DNA',
       subtitle='Bray-Curtis - Species',
       x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  # stat_ellipse(geom = "path", type="norm", level=0.95, aes(color = Secondary.Lab)) +
  scale_color_brewer(palette = 'Set3') +
  theme_dan()
p
```


```{r pcoa fig 1, fig.width=11, fig.height=6, fig.cap="PCoA using species and Bray-Curtis distance."}
# make graph
p <- ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Brassica, shape=Density), color='black') +
  geom_point(size=6) +
  # facet_grid(Soil ~ Plant) +
  scale_fill_brewer(palette = 'Set3') +
  scale_shape_manual(values=c(21,22,23)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 2)))) + # change this number based on the error
  labs(title='PCoA - DNA',
       subtitle='Bray-Curtis - Species',
       x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  # stat_ellipse(geom = "path", type="norm", level=0.95, aes(color = Secondary.Lab)) +
  scale_color_brewer(palette = 'Set3') +
  theme_dan()
p
```

```{r pcoa fig 1, fig.width=11, fig.height=6, fig.cap="PCoA using species and Bray-Curtis distance."}
# make graph
p <- ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Fescue, shape=Density), color='black') +
  geom_point(size=6) +
  # facet_grid(Soil ~ Plant) +
  scale_fill_brewer(palette = 'Set3') +
  scale_shape_manual(values=c(21,22,23)) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 2)))) + # change this number based on the error
  labs(title='PCoA - DNA',
       subtitle='Bray-Curtis - Species',
       x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
  # stat_ellipse(geom = "path", type="norm", level=0.95, aes(color = Secondary.Lab)) +
  scale_color_brewer(palette = 'Set3') +
  theme_dan()
p
```

```{r}
P.relDenDiv <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')
P.relDenDiv <- subset_samples(P.relDenDiv, Type == 'Soil')

plot_bar(P.relDenDiv,
         x = "Density_Diversity",
         fill = "phylum") +
  geom_bar(aes(color = phylum,
               fill = phylum),
           stat = "identity",
           position = "stack")
# theme(legend.position = "NA") + # if legend is distracting, remove it
```

```{r}
P.relDenDiv <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')
P.relDenDiv <- subset_samples(P.relDenDiv, Type == 'Soil')

plot_bar(P.relDenDiv,
         x = "Density_Diversity",
         fill = "order") +
  geom_bar(aes(color = order,
               fill = order),
           stat = "identity",
           position = "stack") +
theme(legend.position = "NA") # if legend is distracting, remove it
```


```{r}
plot_richness(P.relDenDiv, # richness referes to species richness, rerun the first P.relDenDiv if you want the controls
               x = "Density_Diversity",
               measures = c("Shannon"), # shannon is a diversity index
              color = ("Density"), # to see land use and aggregate size
title = ("Shannon Index by Density and Diversity")) +
  labs(x = "Density", 
       color = "Density") +
    geom_boxplot(aes(fill=Diversity))
data(P.relDenDiv)
```
```{r}
plot_richness(P.relDenDiv, # richness referes to species richness, rerun the first P.relDenDiv if you want the controls
               x = "Diversity",
               measures = c("Shannon"), # shannon is a diversity index
              color = ("Density"), # to see land use and aggregate size
title = ("Shannon index for densities and diversities")) +
  labs(x = "Density", 
       color = "Density") +
    geom_boxplot(aes(fill=Diversity))
```

```{r}
plot_richness(P.relDenDiv, # richness referes to species richness, rerun the first P.relDenDiv if you want the controls
               x = "Density",
               measures = c("Shannon"), # shannon is a diversity index
              color = ("Diversity"), # to see land use and aggregate size
title = ("Shannon index for densities, diversities, and controls")) +
  labs(x = "Density", 
       color = "Density") +
    geom_boxplot(aes(fill=Diversity))
```

```{r}
P.relDenDivA <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')
P.relDenDivA <- subset_samples(P.relDenDivA, Alfalfa == 'Alfalfa')

# remove taxa with column sums = 0, this stopped working for some reason
# P.rel = filter_taxa(P.rel, function(x) sum(x) > 0, TRUE)

# get meta data
d <- data.frame(sample_data(P.relDenDivA))

# get otu table for calculating distances
data <- data.frame(t(otu_table(P.relDenDivA)))
# names(data) <- tax_table(P.relDenDivA)[,'species'] # this is for biplot
data <- sqrt(data) # hellinger's transformation (sqrt of rel abund)

# Create distance matrix from PLFA data
dist <- vegdist(data, method='bray')

# now incorporate the biplot
# run PCoA for different treatment groups
ord <- capscale(dist ~ Density * Diversity, data=d)
#summary(ord)

# Optional Biplot
# sppscores(ord) <- data
# biplot <- data.frame(vegan::scores(ord, display='species'))
# biplot <- biplot[abs(biplot$CAP1) > 0.3 | abs(biplot$CAP2) > 0.3, ] # increase the # to see less it was at 0.145

# perMANOVA test
adonis2(dist ~ Density * Diversity, data=d, perm=999, by="margin")
mod <- betadisper(dist, interaction(d$Density, d$Diversity))
mod

### get eigenvalues and proportion explained
ev <- eigenvals(ord)
Axis1_exp = round(ev[1] / sum(ev) * 100, 1)
Axis2_exp = round(ev[2] / sum(ev) * 100, 1)

### get PC axes
axes <- as.data.frame(vegan::scores(ord, display="sites", choices=c(1:2)))
names(axes) <- c("Axis1", "Axis2")
axes <- cbind(d, axes)
```
```{r}
# mult <- 6  #this was for the biplot
AlfalfaDD <- ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity), color='black') +
  geom_point(size=6) +
  scale_shape_manual(values=c(21,22,23,24), labels=c('Alfalfa', 'Alfalfa and Brassica','Alfalfa, Brassica, and Fescue','Alfalfa and Fescue')) +
    scale_fill_manual(labels=c('1', '24','48'), values = c("1" = "indianred1",
                               "24" = "gold",
                               "48" = "green")) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 3)))) +
  labs(title='PCoA - DNA',
       subtitle='Bray-Curtis - Species',
       x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
    stat_ellipse(aes(group=Density)) +
 labs(fill='Density') +
 labs(shape='Diversity') +
  theme_dan() +
    xlim(-3.5,4) +
 theme(plot.title = element_text(size = 26, face = "bold"),
    legend.title=element_text(size=20), 
    legend.text=element_text(size=20)) +
  #Next lines of code were for biplot
#geom_segment(data=biplot, inherit.aes=F, aes(x=0, xend=mult*CAP1, y=0, yend=mult*CAP2), arrow=arrow(length=unit(0.25, 'cm'))) +
# ggrepel::geom_text_repel(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
# geom_text(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
  theme_few()
AlfalfaDD
#ggsave(BipoltAlfalfa, file='/Users/derek_newberger/Desktop/Thesis_CSU/Cover_Crop_Peach/CC_R_Auto_Output/Bipolt_Alfalfa_#NonAutoclaved.pdf', width=11, height=6)
```
```{r}
P.relDenDivB <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')
P.relDenDivB <- subset_samples(P.relDenDivB, Brassica == 'Brassica')

# remove taxa with column sums = 0, this stopped working for some reason
# P.rel = filter_taxa(P.rel, function(x) sum(x) > 0, TRUE)

# get meta data
d <- data.frame(sample_data(P.relDenDivB))

# get otu table for calculating distances
data <- data.frame(t(otu_table(P.relDenDivB)))
names(data) <- tax_table(P.relDenDivB)[,'species']
data <- sqrt(data) # hellinger's transformation (sqrt of rel abund)

# Create distance matrix from PLFA data
dist <- vegdist(data, method='bray')

# now incorporate the biplot
# run PCoA for different treatment groups
ord <- capscale(dist ~ Density * Diversity, data=d)
#summary(ord)

sppscores(ord) <- data
biplot <- data.frame(vegan::scores(ord, display='species'))
biplot <- biplot[abs(biplot$CAP1) > 0.3 | abs(biplot$CAP2) > 0.3, ] # increase the # to see less it was at 0.145

# perMANOVA test
adonis2(dist ~ Density * Diversity, data=d, perm=999, by="margin")
mod <- betadisper(dist, interaction(d$Density, d$Diversity))
mod

### get eigenvalues and proportion explained
ev <- eigenvals(ord)
Axis1_exp = round(ev[1] / sum(ev) * 100, 1)
Axis2_exp = round(ev[2] / sum(ev) * 100, 1)

### get PC axes
axes <- as.data.frame(vegan::scores(ord, display="sites", choices=c(1:2)))
names(axes) <- c("Axis1", "Axis2")
axes <- cbind(d, axes)
```

```{r}
mult <- 6
BipoltBrassicaDD <- ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity), color='black') +
  geom_point(size=6) +
  scale_shape_manual(values=c(21,22,23,24), labels=c('Alfalfa and Brassica', 'Alfalfa, Brassica, and Fescue','Brassica', 'Brassica and Fescue')) +
    scale_fill_manual(labels=c('1', '24','48'), values = c("1" = "indianred1",
                               "24" = "gold",
                               "48" = "green")) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 3)))) +
  labs(title='PCoA - DNA',
       subtitle='Bray-Curtis - Species',
       x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
    stat_ellipse(aes(group=Density)) +
 labs(fill='Density') +
 labs(shape='Diversity') +
  theme_dan() +
    xlim(-3.5,4) +
 theme(plot.title = element_text(size = 26, face = "bold"),
    legend.title=element_text(size=20), 
    legend.text=element_text(size=20)) +
    geom_segment(data=biplot, inherit.aes=F, aes(x=0, xend=mult*CAP1, y=0, yend=mult*CAP2), arrow=arrow(length=unit(0.25, 'cm'))) +
ggrepel::geom_text_repel(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
geom_text(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
  theme_few()
BipoltBrassicaDD
#ggsave(BipoltAlfalfa, file='/Users/derek_newberger/Desktop/Thesis_CSU/Cover_Crop_Peach/CC_R_Auto_Output/Bipolt_Alfalfa_#NonAutoclaved.pdf', width=11, height=6)
```

```{r}
P.relDenDivF <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')
P.relDenDivF <- subset_samples(P.relDenDivF, Fescue == 'Fescue')

# remove taxa with column sums = 0, this stopped working for some reason
# P.rel = filter_taxa(P.rel, function(x) sum(x) > 0, TRUE)

# get meta data
d <- data.frame(sample_data(P.relDenDivF))

# get otu table for calculating distances
data <- data.frame(t(otu_table(P.relDenDivF)))
names(data) <- tax_table(P.relDenDivF)[,'species']
data <- sqrt(data) # hellinger's transformation (sqrt of rel abund)

# Create distance matrix from PLFA data
dist <- vegdist(data, method='bray')

# now incorporate the biplot
# run PCoA for different treatment groups
ord <- capscale(dist ~ Density * Diversity, data=d)
#summary(ord)

sppscores(ord) <- data
biplot <- data.frame(vegan::scores(ord, display='species'))
biplot <- biplot[abs(biplot$CAP1) > 0.3 | abs(biplot$CAP2) > 0.3, ] # increase the # to see less it was at 0.145

# perMANOVA test
adonis2(dist ~ Density * Diversity, data=d, perm=999, by="margin")
mod <- betadisper(dist, interaction(d$Density, d$Diversity))
mod

### get eigenvalues and proportion explained
ev <- eigenvals(ord)
Axis1_exp = round(ev[1] / sum(ev) * 100, 1)
Axis2_exp = round(ev[2] / sum(ev) * 100, 1)

### get PC axes
axes <- as.data.frame(vegan::scores(ord, display="sites", choices=c(1:2)))
names(axes) <- c("Axis1", "Axis2")
axes <- cbind(d, axes)
```

```{r}
mult <- 6
BipoltFescueDD <- ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity), color='black') +
  geom_point(size=6) +
  scale_shape_manual(values=c(21,22,23,24), labels=c('Alfalfa, Brassica, and Fescue','Alfalfa and Fescue', 'Brassica and Fescue', 'Fescue')) +
    scale_fill_manual(labels=c('1', '24','48'), values = c("1" = "indianred1",
                               "24" = "gold",
                               "48" = "green")) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 3)))) +
  labs(title='PCoA - DNA',
       subtitle='Bray-Curtis - Species',
       x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
    stat_ellipse(aes(group=Density)) +
 labs(fill='Density') +
 labs(shape='Diversity') +
  theme_dan() +
    xlim(-3.5,4) +
 theme(plot.title = element_text(size = 26, face = "bold"),
    legend.title=element_text(size=20), 
    legend.text=element_text(size=20)) +
    geom_segment(data=biplot, inherit.aes=F, aes(x=0, xend=mult*CAP1, y=0, yend=mult*CAP2), arrow=arrow(length=unit(0.25, 'cm'))) +
ggrepel::geom_text_repel(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
geom_text(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
  theme_few()
BipoltFescueDD
#ggsave(BipoltAlfalfa, file='/Users/derek_newberger/Desktop/Thesis_CSU/Cover_Crop_Peach/CC_R_Auto_Output/Bipolt_Alfalfa_#NonAutoclaved.pdf', width=11, height=6)
```
```{r}
P.relMonoF <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')
P.relMonoF <- subset_samples(P.relMonoF, Monoculture == 'Fescue')

# remove taxa with column sums = 0, this stopped working for some reason
# P.rel = filter_taxa(P.rel, function(x) sum(x) > 0, TRUE)

# get meta data
d <- data.frame(sample_data(P.relMonoF))

# get otu table for calculating distances
data <- data.frame(t(otu_table(P.relMonoF)))
# names(data) <- tax_table(P.relMonoF)[,'species'] for biplot
data <- sqrt(data) # hellinger's transformation (sqrt of rel abund)

# Create distance matrix from PLFA data
dist <- vegdist(data, method='bray')

# now incorporate the biplot
# run PCoA for different treatment groups
ord <- capscale(dist ~ Density, data=d)
#summary(ord)

# sppscores(ord) <- data
# biplot <- data.frame(vegan::scores(ord, display='species'))
# biplot <- biplot[abs(biplot$CAP1) > 0.15 | abs(biplot$CAP2) > 0.15, ] # increase the # to see less it was at 0.145

# perMANOVA test
adonis2(dist ~ Density, data=d, perm=999, by="margin")
mod <- betadisper(dist, d$Density)
mod

### get eigenvalues and proportion explained
ev <- eigenvals(ord)
Axis1_exp = round(ev[1] / sum(ev) * 100, 1)
Axis2_exp = round(ev[2] / sum(ev) * 100, 1)

### get PC axes
axes <- as.data.frame(vegan::scores(ord, display="sites", choices=c(1:2)))
names(axes) <- c("Axis1", "Axis2")
axes <- cbind(d, axes)
```

```{r}
# mult <- 6
MonoFescue <- ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity), color='black') +
  geom_point(size=6) +
  scale_shape_manual(values=c(21,22,23,24), labels=c('Fescue')) +
    scale_fill_manual(labels=c('1', '24','48'), values = c("1" = "indianred1",
                               "24" = "gold",
                               "48" = "green")) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 3)))) +
  labs(title='PCoA - DNA',
       subtitle='Bray-Curtis - Species',
       x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
    stat_ellipse(aes(group=Density)) +
 labs(fill='Density') +
 labs(shape='Diversity') +
  theme_dan() +
    xlim(-3.5,4) +
 theme(plot.title = element_text(size = 26, face = "bold"),
    legend.title=element_text(size=20), 
    legend.text=element_text(size=20)) +
# geom_segment(data=biplot, inherit.aes=F, aes(x=0, xend=mult*CAP1, y=0, yend=mult*CAP2), arrow=arrow(length=unit(0.25, 'cm'))) +
# ggrepel::geom_text_repel(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
# geom_text(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
  theme_few()
MonoFescue
#ggsave(BipoltAlfalfa, file='/Users/derek_newberger/Desktop/Thesis_CSU/Cover_Crop_Peach/CC_R_Auto_Output/Bipolt_Alfalfa_#NonAutoclaved.pdf', width=11, height=6)
```

```{r}
P.relMonoA <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')
P.relMonoA <- subset_samples(P.relMonoA, Monoculture == 'Alfalfa')

# remove taxa with column sums = 0, this stopped working for some reason
# P.rel = filter_taxa(P.rel, function(x) sum(x) > 0, TRUE)

# get meta data
d <- data.frame(sample_data(P.relMonoA))

# get otu table for calculating distances
data <- data.frame(t(otu_table(P.relMonoA)))
# names(data) <- tax_table(P.relMonoA)[,'species']
data <- sqrt(data) # hellinger's transformation (sqrt of rel abund)

# Create distance matrix from PLFA data
dist <- vegdist(data, method='bray')

# now incorporate the biplot
# run PCoA for different treatment groups
ord <- capscale(dist ~ Density, data=d)
#summary(ord)

# sppscores(ord) <- data
# biplot <- data.frame(vegan::scores(ord, display='species'))
# biplot <- biplot[abs(biplot$CAP1) > 0.2 | abs(biplot$CAP2) > 0.2, ] # increase the # to see less it was at 0.145

# perMANOVA test
adonis2(dist ~ Density, data=d, perm=999, by="margin")
mod <- betadisper(dist, d$Density)
mod

### get eigenvalues and proportion explained
ev <- eigenvals(ord)
Axis1_exp = round(ev[1] / sum(ev) * 100, 1)
Axis2_exp = round(ev[2] / sum(ev) * 100, 1)

### get PC axes
axes <- as.data.frame(vegan::scores(ord, display="sites", choices=c(1:2)))
names(axes) <- c("Axis1", "Axis2")
axes <- cbind(d, axes)
```


```{r}
# mult <- 6
MonoAlfalfa <- ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity), color='black') +
  geom_point(size=6) +
  scale_shape_manual(values=c(21,22,23,24), labels=c('Alfalfa')) +
    scale_fill_manual(labels=c('1', '24','48'), values = c("1" = "indianred1",
                               "24" = "gold",
                               "48" = "green")) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 3)))) +
  labs(title='PCoA - DNA',
       subtitle='Bray-Curtis - Species',
       x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
    stat_ellipse(aes(group=Density)) +
 labs(fill='Density') +
 labs(shape='Diversity') +
  theme_dan() +
    xlim(-3.5,4) +
 theme(plot.title = element_text(size = 26, face = "bold"),
    legend.title=element_text(size=20), 
    legend.text=element_text(size=20)) +
# geom_segment(data=biplot, inherit.aes=F, aes(x=0, xend=mult*CAP1, y=0, yend=mult*CAP2), arrow=arrow(length=unit(0.25, 'cm'))) +
# ggrepel::geom_text_repel(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
# geom_text(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
  theme_few()
MonoAlfalfa
#ggsave(BipoltAlfalfa, file='/Users/derek_newberger/Desktop/Thesis_CSU/Cover_Crop_Peach/CC_R_Auto_Output/Bipolt_Alfalfa_#NonAutoclaved.pdf', width=11, height=6)
```
```{r}
P.relMonoB <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')
P.relMonoB <- subset_samples(P.relMonoB, Monoculture == 'Brassica')

# remove taxa with column sums = 0, this stopped working for some reason
# P.rel = filter_taxa(P.rel, function(x) sum(x) > 0, TRUE)

# get meta data
d <- data.frame(sample_data(P.relMonoB))

# get otu table for calculating distances
data <- data.frame(t(otu_table(P.relMonoB)))
# names(data) <- tax_table(P.relMonoB)[,'species'] for biplot
data <- sqrt(data) # hellinger's transformation (sqrt of rel abund)

# Create distance matrix from PLFA data
dist <- vegdist(data, method='bray')

# now incorporate the biplot
# run PCoA for different treatment groups
ord <- capscale(dist ~ Density, data=d)
#summary(ord)

# sppscores(ord) <- data
# biplot <- data.frame(vegan::scores(ord, display='species'))
# biplot <- biplot[abs(biplot$CAP1) > 0.1 | abs(biplot$CAP2) > 0.1, ] # increase the # to see less it was at 0.145

# perMANOVA test
adonis2(dist ~ Density, data=d, perm=999, by="margin")
mod <- betadisper(dist, d$Density)
mod

### get eigenvalues and proportion explained
ev <- eigenvals(ord)
Axis1_exp = round(ev[1] / sum(ev) * 100, 1)
Axis2_exp = round(ev[2] / sum(ev) * 100, 1)

### get PC axes
axes <- as.data.frame(vegan::scores(ord, display="sites", choices=c(1:2)))
names(axes) <- c("Axis1", "Axis2")
axes <- cbind(d, axes)
```

```{r}
# mult <- 6
MonoBrassica <- ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity), color='black') +
  geom_point(size=6) +
  scale_shape_manual(values=c(21,22,23,24), labels=c('Brassica')) +
    scale_fill_manual(labels=c('1', '24','48'), values = c("1" = "indianred1",
                               "24" = "gold",
                               "48" = "green")) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 3)))) +
  labs(title='PCoA - DNA',
       subtitle='Bray-Curtis - Species',
       x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
    stat_ellipse(aes(group=Density)) +
 labs(fill='Density') +
 labs(shape='Diversity') +
  theme_dan() +
    xlim(-3.5,4) +
 theme(plot.title = element_text(size = 26, face = "bold"),
    legend.title=element_text(size=20), 
    legend.text=element_text(size=20)) +
# geom_segment(data=biplot, inherit.aes=F, aes(x=0, xend=mult*CAP1, y=0, yend=mult*CAP2), arrow=arrow(length=unit(0.25, 'cm'))) +
# ggrepel::geom_text_repel(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
# geom_text(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
  theme_few()
MonoBrassica
#ggsave(BipoltMonoBrassica, file='/Users/derek_newberger/Desktop/Thesis_CSU/Cover_Crop_Peach/CC_R_Auto_Output/BipoltMonoBrassica.pdf', width=11, height=6)
```

```{r}
sample_data(P.relDenDiv)
otu_table(P.relDenDiv)
tax_table(P.relDenDiv)

P.sub <- subset_samples(P.relDenDiv, Type == "Soil")
P.sub <- subset_taxa(P.sub, species %in% c('Parasegetibacter luojiensis'))
samp <- data.frame(sample_data(P.sub)) # rows are samples
samp$sample_name <- row.names(samp)

abund <- as.data.frame(otu_table(P.sub)) # rows are taxa
abund <- as.data.frame(t(abund)) # rows are samples
colnames(abund) <- c('Parasegetibacter luojiensis')
abund$sample <- row.names(abund)

df <- samp %>%
  left_join(abund, by=c('sample_name' = 'sample'))
```

```{r}
p <- ggplot(df, aes(x=Density, y=`Parasegetibacter luojiensis`)) +
  geom_boxplot(aes(fill=Diversity))
print(p)
```
```{r}
P.relPolyABF <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')
P.relPolyABF <- subset_samples(P.relPolyABF, Diversity == 'ABF')

# remove taxa with column sums = 0, this stopped working for some reason
# P.rel = filter_taxa(P.rel, function(x) sum(x) > 0, TRUE)

# get meta data
d <- data.frame(sample_data(P.relPolyABF))

# get otu table for calculating distances
data <- data.frame(t(otu_table(P.relPolyABF)))
names(data) <- tax_table(P.relPolyABF)[,'species']
data <- sqrt(data) # hellinger's transformation (sqrt of rel abund)

# Create distance matrix from PLFA data
dist <- vegdist(data, method='bray')

# now incorporate the biplot
# run PCoA for different treatment groups
ord <- capscale(dist ~ Density, data=d)
#summary(ord)

# sppscores(ord) <- data
# biplot <- data.frame(vegan::scores(ord, display='species'))
# biplot <- biplot[abs(biplot$CAP1) > 0.2 | abs(biplot$CAP2) > 0.2, ] # increase the # to see less it was at 0.145

# perMANOVA test
adonis2(dist ~ Density, data=d, perm=999, by="margin")
mod <- betadisper(dist, d$Density)
mod

### get eigenvalues and proportion explained
ev <- eigenvals(ord)
Axis1_exp = round(ev[1] / sum(ev) * 100, 1)
Axis2_exp = round(ev[2] / sum(ev) * 100, 1)

### get PC axes
axes <- as.data.frame(vegan::scores(ord, display="sites", choices=c(1:2)))
names(axes) <- c("Axis1", "Axis2")
axes <- cbind(d, axes)
```
```{r}
mult <- 6
BipoltPolyABF <- ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity), color='black') +
  geom_point(size=6) +
  scale_shape_manual(values=c(21,22,23,24), labels=c('Alfalfa, Brassica, and Fescue')) +
    scale_fill_manual(labels=c('3', '24','48'), values = c("1" = "indianred1",
                               "24" = "gold",
                               "48" = "green")) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 3)))) +
  labs(title='PCoA - DNA',
       subtitle='Bray-Curtis - Species',
       x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
    stat_ellipse(aes(group=Density)) +
 labs(fill='Density') +
 labs(shape='Diversity') +
  theme_dan() +
    xlim(-3.5,4) +
 theme(plot.title = element_text(size = 26, face = "bold"),
    legend.title=element_text(size=20), 
    legend.text=element_text(size=20)) +
    # geom_segment(data=biplot, inherit.aes=F, aes(x=0, xend=mult*CAP1, y=0, yend=mult*CAP2), arrow=arrow(length=unit(0.25, 'cm'))) +
#ggrepel::geom_text_repel(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
# geom_text(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
  theme_few()
BipoltPolyABF
#ggsave(BipoltAlfalfa, file='/Users/derek_newberger/Desktop/Thesis_CSU/Cover_Crop_Peach/CC_R_Auto_Output/Bipolt_Alfalfa_#NonAutoclaved.pdf', width=11, height=6)
```
```{r}
P.relPolyAB <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')
P.relPolyAB <- subset_samples(P.relPolyAB, Diversity == 'AB')

# remove taxa with column sums = 0, this stopped working for some reason
# P.rel = filter_taxa(P.rel, function(x) sum(x) > 0, TRUE)

# get meta data
d <- data.frame(sample_data(P.relPolyAB))

# get otu table for calculating distances
data <- data.frame(t(otu_table(P.relPolyAB)))
names(data) <- tax_table(P.relPolyAB)[,'species']
data <- sqrt(data) # hellinger's transformation (sqrt of rel abund)

# Create distance matrix from PLFA data
dist <- vegdist(data, method='bray')

# now incorporate the biplot
# run PCoA for different treatment groups
ord <- capscale(dist ~ Density, data=d)
#summary(ord)

# sppscores(ord) <- data
# biplot <- data.frame(vegan::scores(ord, display='species'))
# biplot <- biplot[abs(biplot$CAP1) > 0.2 | abs(biplot$CAP2) > 0.2, ] # increase the # to see less it was at 0.145

# perMANOVA test
adonis2(dist ~ Density, data=d, perm=999, by="margin")
mod <- betadisper(dist, d$Density)
mod

### get eigenvalues and proportion explained
ev <- eigenvals(ord)
Axis1_exp = round(ev[1] / sum(ev) * 100, 1)
Axis2_exp = round(ev[2] / sum(ev) * 100, 1)

### get PC axes
axes <- as.data.frame(vegan::scores(ord, display="sites", choices=c(1:2)))
names(axes) <- c("Axis1", "Axis2")
axes <- cbind(d, axes)
```

```{r}
mult <- 6
BipoltPolyAB <- ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity), color='black') +
  geom_point(size=6) +
  scale_shape_manual(values=c(21,22,23,24), labels=c('Alfalfa and Brassica')) +
    scale_fill_manual(labels=c('2', '24','48'), values = c("1" = "indianred1",
                               "24" = "gold",
                               "48" = "green")) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 3)))) +
  labs(title='PCoA - DNA',
       subtitle='Bray-Curtis - Species',
       x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
    stat_ellipse(aes(group=Density)) +
 labs(fill='Density') +
 labs(shape='Diversity') +
  theme_dan() +
    xlim(-3.5,4) +
 theme(plot.title = element_text(size = 26, face = "bold"),
    legend.title=element_text(size=20), 
    legend.text=element_text(size=20)) +
    # geom_segment(data=biplot, inherit.aes=F, aes(x=0, xend=mult*CAP1, y=0, yend=mult*CAP2), arrow=arrow(length=unit(0.25, 'cm'))) +
# ggrepel::geom_text_repel(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
# geom_text(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
  theme_few()
BipoltPolyAB
#ggsave(BipoltAlfalfa, file='/Users/derek_newberger/Desktop/Thesis_CSU/Cover_Crop_Peach/CC_R_Auto_Output/Bipolt_Alfalfa_#NonAutoclaved.pdf', width=11, height=6)
```
```{r}
P.relPolyAF <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')
P.relPolyAF <- subset_samples(P.relPolyAF, Diversity == 'AF')

# remove taxa with column sums = 0, this stopped working for some reason
# P.rel = filter_taxa(P.rel, function(x) sum(x) > 0, TRUE)

# get meta data
d <- data.frame(sample_data(P.relPolyAF))

# get otu table for calculating distances
data <- data.frame(t(otu_table(P.relPolyAF)))
names(data) <- tax_table(P.relPolyAF)[,'species']
data <- sqrt(data) # hellinger's transformation (sqrt of rel abund)

# Create distance matrix from PLFA data
dist <- vegdist(data, method='bray')

# now incorporate the biplot
# run PCoA for different treatment groups
ord <- capscale(dist ~ Density, data=d)
#summary(ord)

# sppscores(ord) <- data
# biplot <- data.frame(vegan::scores(ord, display='species'))
# biplot <- biplot[abs(biplot$CAP1) > 0.1 | abs(biplot$CAP2) > 0.1, ] # increase the # to see less it was at 0.145

# perMANOVA test
adonis2(dist ~ Density, data=d, perm=999, by="margin")
mod <- betadisper(dist, d$Density)
mod

### get eigenvalues and proportion explained
ev <- eigenvals(ord)
Axis1_exp = round(ev[1] / sum(ev) * 100, 1)
Axis2_exp = round(ev[2] / sum(ev) * 100, 1)

### get PC axes
axes <- as.data.frame(vegan::scores(ord, display="sites", choices=c(1:2)))
names(axes) <- c("Axis1", "Axis2")
axes <- cbind(d, axes)
```
```{r}
mult <- 6
BipoltPolyAF <- ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity), color='black') +
  geom_point(size=6) +
  scale_shape_manual(values=c(21,22,23,24), labels=c('Alfalfa and Fescue')) +
    scale_fill_manual(labels=c('2', '24','48'), values = c("1" = "indianred1",
                               "24" = "gold",
                               "48" = "green")) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 3)))) +
  labs(title='PCoA - DNA',
       subtitle='Bray-Curtis - Species',
       x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
    stat_ellipse(aes(group=Density)) +
 labs(fill='Density') +
 labs(shape='Diversity') +
  theme_dan() +
    xlim(-3.5,4) +
 theme(plot.title = element_text(size = 26, face = "bold"),
    legend.title=element_text(size=20), 
    legend.text=element_text(size=20)) +
    # geom_segment(data=biplot, inherit.aes=F, aes(x=0, xend=mult*CAP1, y=0, yend=mult*CAP2), arrow=arrow(length=unit(0.25, 'cm'))) +
# ggrepel::geom_text_repel(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
 # ggrepel::geom_text_repel(data=biplot, max.overlaps = getOption("ggrepel.max.overlaps", default = 20), inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
  theme_few()
BipoltPolyAF
ggsave(BipoltPolyAF, file='/Users/derek_newberger/Desktop/Thesis_CSU/Cover_Crop_Peach/CC_R_Auto_Output/BipoltPolyAF.pdf', width=11, height=6)
```
```{r}
P.relPolyBF <- readRDS('/Users/derek_newberger/Desktop/Thesis_CSU/Density_Diversity/DD_R_Auto_Output/P.relDenDiv.RDS')
P.relPolyBF <- subset_samples(P.relPolyBF, Diversity == 'BF')

# remove taxa with column sums = 0, this stopped working for some reason
# P.rel = filter_taxa(P.rel, function(x) sum(x) > 0, TRUE)

# get meta data
d <- data.frame(sample_data(P.relPolyBF))

# get otu table for calculating distances
data <- data.frame(t(otu_table(P.relPolyBF)))
names(data) <- tax_table(P.relPolyBF)[,'species']
data <- sqrt(data) # hellinger's transformation (sqrt of rel abund)

# Create distance matrix from PLFA data
dist <- vegdist(data, method='bray')

# now incorporate the biplot
# run PCoA for different treatment groups
ord <- capscale(dist ~ Density, data=d)
#summary(ord)

# sppscores(ord) <- data
# biplot <- data.frame(vegan::scores(ord, display='species'))
# biplot <- biplot[abs(biplot$CAP1) > 0.1 | abs(biplot$CAP2) > 0.1, ] # increase the # to see less it was at 0.145

# perMANOVA test
adonis2(dist ~ Density, data=d, perm=999, by="margin")
mod <- betadisper(dist, d$Density)
mod

### get eigenvalues and proportion explained
ev <- eigenvals(ord)
Axis1_exp = round(ev[1] / sum(ev) * 100, 1)
Axis2_exp = round(ev[2] / sum(ev) * 100, 1)

### get PC axes
axes <- as.data.frame(vegan::scores(ord, display="sites", choices=c(1:2)))
names(axes) <- c("Axis1", "Axis2")
axes <- cbind(d, axes)
```
```{r}
mult <- 6
BipoltPolyBF <- ggplot(data=axes, aes(x=Axis1, y=Axis2, fill=Density, shape=Diversity), color='black') +
  geom_point(size=6) +
  scale_shape_manual(values=c(21,22,23,24), labels=c('Brassica and Fescue')) +
    scale_fill_manual(labels=c('2', '24','48'), values = c("1" = "indianred1",
                               "24" = "gold",
                               "48" = "green")) +
  guides(fill = guide_legend(
    override.aes=list(shape = rep(21, 3)))) +
  labs(title='PCoA - DNA',
       subtitle='Bray-Curtis - Species',
       x=paste0('CAP1 (', Axis1_exp, '%)'), 
       y=paste0('CAP2 (', Axis2_exp, '%)')) +
    stat_ellipse(aes(group=Density)) +
 labs(fill='Density') +
 labs(shape='Diversity') +
  theme_dan() +
    xlim(-3.5,4) +
 theme(plot.title = element_text(size = 26, face = "bold"),
    legend.title=element_text(size=20), 
    legend.text=element_text(size=20)) +
    # geom_segment(data=biplot, inherit.aes=F, aes(x=0, xend=mult*CAP1, y=0, yend=mult*CAP2), arrow=arrow(length=unit(0.25, 'cm'))) +
# ggrepel::geom_text_repel(data=biplot, inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
 # ggrepel::geom_text_repel(data=biplot, max.overlaps = getOption("ggrepel.max.overlaps", default = 20), inherit.aes=F, aes(x=mult*CAP1, y=mult*CAP2, label=row.names(biplot))) +
  theme_few()
BipoltPolyBF
ggsave(BipoltPolyBF, file='/Users/derek_newberger/Desktop/Thesis_CSU/Cover_Crop_Peach/CC_R_Auto_Output/BipoltPolyBF.pdf', width=11, height=6)
```

```{r}
P.sub <- subset_samples(P.relDenDiv, Type == "Soil")
P.sub <- subset_taxa(P.sub, species %in% c('Ensifer adhaerens'))
samp <- data.frame(sample_data(P.sub)) # rows are samples
samp$sample_name <- row.names(samp)

abund <- as.data.frame(otu_table(P.sub)) # rows are taxa
abund <- as.data.frame(t(abund)) # rows are samples
colnames(abund) <- c('Ensifer adhaerens')
abund$sample <- row.names(abund)

df <- samp %>%
  left_join(abund, by=c('sample_name' = 'sample'))
```

```{r}
p <- ggplot(df, aes(x=Density, y=`Ensifer adhaerens`)) +
  geom_boxplot(aes(fill=Diversity))
print(p)
```
```{r}
P.sub <- subset_samples(P.relDenDiv, Type == "Soil")
P.sub <- subset_taxa(P.sub, species %in% c('Azospirillum sp. TSA2s'))
samp <- data.frame(sample_data(P.sub)) # rows are samples
samp$sample_name <- row.names(samp)

abund <- as.data.frame(otu_table(P.sub)) # rows are taxa
abund <- as.data.frame(t(abund)) # rows are samples
colnames(abund) <- c('Azospirillum sp. TSA2s')
abund$sample <- row.names(abund)

df <- samp %>%
  left_join(abund, by=c('sample_name' = 'sample'))
```

```{r}
p <- ggplot(df, aes(x=Density, y=`Azospirillum sp. TSA2s`)) +
  geom_boxplot(aes(fill=Diversity))
print(p)
```

```{r}
P.sub <- subset_samples(P.relDenDiv, Type == "Soil")
P.sub <- subset_taxa(P.sub, species %in% c('Stenotrophomonas sp. DAIF1'))
samp <- data.frame(sample_data(P.sub)) # rows are samples
samp$sample_name <- row.names(samp)

abund <- as.data.frame(otu_table(P.sub)) # rows are taxa
abund <- as.data.frame(t(abund)) # rows are samples
colnames(abund) <- c('Stenotrophomonas sp. DAIF1')
abund$sample <- row.names(abund)

df <- samp %>%
  left_join(abund, by=c('sample_name' = 'sample'))
```

```{r}
p <- ggplot(df, aes(x=Density, y=`Stenotrophomonas sp. DAIF1`)) +
  geom_boxplot(aes(fill=Diversity))
print(p)
```
```{r}
P.sub <- subset_samples(P.relDenDiv, Type == "Soil")
P.sub <- subset_taxa(P.sub, species %in% c('Roseomonas aestuarii'))
samp <- data.frame(sample_data(P.sub)) # rows are samples
samp$sample_name <- row.names(samp)

abund <- as.data.frame(otu_table(P.sub)) # rows are taxa
abund <- as.data.frame(t(abund)) # rows are samples
colnames(abund) <- c('Roseomonas aestuarii')
abund$sample <- row.names(abund)

df <- samp %>%
  left_join(abund, by=c('sample_name' = 'sample'))
```

```{r}
p <- ggplot(df, aes(x=Density, y=`Roseomonas aestuarii`)) +
  geom_boxplot(aes(fill=Diversity))
print(p)
```
```{r}
P.sub <- subset_samples(P.relDenDiv, Type == "Soil")
P.sub <- subset_taxa(P.sub, species %in% c('Ammoniphilus oxalaticus'))
samp <- data.frame(sample_data(P.sub)) # rows are samples
samp$sample_name <- row.names(samp)

abund <- as.data.frame(otu_table(P.sub)) # rows are taxa
abund <- as.data.frame(t(abund)) # rows are samples
colnames(abund) <- c('Ammoniphilus oxalaticus')
abund$sample <- row.names(abund)

df <- samp %>%
  left_join(abund, by=c('sample_name' = 'sample'))
```

```{r}
p <- ggplot(df, aes(x=Density, y=`Ammoniphilus oxalaticus`)) +
  geom_boxplot(aes(fill=Diversity))
print(p)
```

```{r}
P.sub <- subset_samples(P.relDenDiv, Type == "Soil")
P.sub <- subset_taxa(P.sub, species %in% c('Azospirillum lipoferum'))
samp <- data.frame(sample_data(P.sub)) # rows are samples
samp$sample_name <- row.names(samp)

abund <- as.data.frame(otu_table(P.sub)) # rows are taxa
abund <- as.data.frame(t(abund)) # rows are samples
colnames(abund) <- c('Azospirillum lipoferum')
abund$sample <- row.names(abund)

df <- samp %>%
  left_join(abund, by=c('sample_name' = 'sample'))
```

```{r}
p <- ggplot(df, aes(x=Density, y=`Azospirillum lipoferum`)) +
  geom_boxplot(aes(fill=Diversity))
print(p)
```

```{r}
P.sub <- subset_samples(P.relDenDiv, Type == "Soil")
P.sub <- subset_taxa(P.sub, species %in% c('Pontibacter akesuensis'))
samp <- data.frame(sample_data(P.sub)) # rows are samples
samp$sample_name <- row.names(samp)

abund <- as.data.frame(otu_table(P.sub)) # rows are taxa
abund <- as.data.frame(t(abund)) # rows are samples
colnames(abund) <- c('Pontibacter akesuensis')
abund$sample <- row.names(abund)

df <- samp %>%
  left_join(abund, by=c('sample_name' = 'sample'))
```

```{r}
p <- ggplot(df, aes(x=Density, y=`Pontibacter akesuensis`)) +
  geom_boxplot(aes(fill=Diversity))
print(p)
```

```{r}
P.sub <- subset_samples(P.relDenDiv, Type == "Soil")
P.sub <- subset_taxa(P.sub, species %in% c('Pseudoxanthomonas mexicana'))
samp <- data.frame(sample_data(P.sub)) # rows are samples
samp$sample_name <- row.names(samp)

abund <- as.data.frame(otu_table(P.sub)) # rows are taxa
abund <- as.data.frame(t(abund)) # rows are samples
colnames(abund) <- c('Pseudoxanthomonas mexicana')
abund$sample <- row.names(abund)

df <- samp %>%
  left_join(abund, by=c('sample_name' = 'sample'))
```

```{r}
p <- ggplot(df, aes(x=Density, y=`Pseudoxanthomonas mexicana`)) +
  geom_boxplot(aes(fill=Diversity))
print(p)
```

```{r}
P.sub <- subset_samples(P.relDenDiv, Type == "Soil")
P.sub <- subset_taxa(P.sub, species %in% c('Lysobacter sp. TY2-98'))
samp <- data.frame(sample_data(P.sub)) # rows are samples
samp$sample_name <- row.names(samp)

abund <- as.data.frame(otu_table(P.sub)) # rows are taxa
abund <- as.data.frame(t(abund)) # rows are samples
colnames(abund) <- c('Lysobacter sp. TY2-98')
abund$sample <- row.names(abund)

df <- samp %>%
  left_join(abund, by=c('sample_name' = 'sample'))
```

```{r}
p <- ggplot(df, aes(x=Density, y=`Lysobacter sp. TY2-98`)) +
  geom_boxplot(aes(fill=Diversity))
print(p)
```

```{r}
P.sub <- subset_samples(P.relDenDiv, Type == "Soil")
P.sub <- subset_taxa(P.sub, species %in% c('Devosia limi'))
samp <- data.frame(sample_data(P.sub)) # rows are samples
samp$sample_name <- row.names(samp)

abund <- as.data.frame(otu_table(P.sub)) # rows are taxa
abund <- as.data.frame(t(abund)) # rows are samples
colnames(abund) <- c('Devosia limi')
abund$sample <- row.names(abund)

df <- samp %>%
  left_join(abund, by=c('sample_name' = 'sample'))
```

```{r}
p <- ggplot(df, aes(x=Density, y=`Devosia limi`)) +
  geom_boxplot(aes(fill=Diversity))
print(p)
```
```{r}
P.sub <- subset_samples(P.relDenDiv, Type == "Soil")
P.sub <- subset_taxa(P.sub, species %in% c('Pseudarthrobacter polychromogenes'))
samp <- data.frame(sample_data(P.sub)) # rows are samples
samp$sample_name <- row.names(samp)

abund <- as.data.frame(otu_table(P.sub)) # rows are taxa
abund <- as.data.frame(t(abund)) # rows are samples
colnames(abund) <- c('Pseudarthrobacter polychromogenes')
abund$sample <- row.names(abund)

df <- samp %>%
  left_join(abund, by=c('sample_name' = 'sample'))
```

```{r}
p <- ggplot(df, aes(x=Density, y=`Pseudarthrobacter polychromogenes`)) +
  geom_boxplot(aes(fill=Diversity))
print(p)
```

```{r}
P.sub <- subset_samples(P.relDenDiv, Type == "Soil")
P.sub <- subset_taxa(P.sub, species %in% c('Trichormus variabilis'))
samp <- data.frame(sample_data(P.sub)) # rows are samples
samp$sample_name <- row.names(samp)

abund <- as.data.frame(otu_table(P.sub)) # rows are taxa
abund <- as.data.frame(t(abund)) # rows are samples
colnames(abund) <- c('Trichormus variabilis')
abund$sample <- row.names(abund)

df <- samp %>%
  left_join(abund, by=c('sample_name' = 'sample'))
```

```{r}
p <- ggplot(df, aes(x=Density, y=`Trichormus variabilis`)) +
  geom_boxplot(aes(fill=Diversity))
print(p)
```



